import type { Metadata } from "next";
import Link from "next/link";
import { Geist, JetBrains_Mono, DM_Sans } from "next/font/google";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import "./globals.css";

const calSans = localFont({
  src: "./fonts/CalSans-SemiBold.woff2",
  variable: "--font-cal-sans",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${jetbrainsMono.variable} ${dmSans.variable} ${calSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#F7F6F4] dark:bg-[#0a0a0a] font-sans text-zinc-900 dark:text-zinc-50">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
